name: master Build Matrix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-20.04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build-ubuntu-18.04:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build-ubuntu-16.04:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
