name: master Build Matrix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
